protocol = "labjack-sensor"
doc = ""
traits = ["has-measure-trigger", "is-sensor", "is-daemon"]
hardware = ["labjack:t7-pro"]

[links]
source = "https://github.com/yaq-project/yaqd-labjack"
bugtracker = "https://github.com/yaq-project/yaqd-labjack/-/issues"
example-configs = "https://github.com/yaq-project/yaqd-labjack/tree/main/example-yaq-configs/labjack-sensor"

[installation]
PyPI = "https://pypi.org/project/yaqd-labjack"

[[types]]
type = "enum"
name = "modbus_type"
symbols = ["float32", "uint16", "uint32", "int32"]

[[types]]
type = "record"
name = "channel"
fields = [{"name"="modbus_address", "type"="int"},
          {"name"="modbus_type", "type"="modbus_type"},
	  {"name"="units", "type"=["string", "null"], "default"="__null__"},
          {"name"="enabled", "type"="boolean", "default"=true}]

[[types]]
type = "record"
name = "setting"
fields = [{"name"="modbus_address", "type"="int"},
          {"name"="modbus_type", "type"="modbus_type"},
	  {"name"="value", "type"=["double", "long"]},
	  {"name"="comment", "type"="string", "doc"="comment for human consumption"},
          {"name"="enabled", "type"="boolean", "default"=true}]

[config]

[config.channels]
type = "map"
values = "channel"
default = {}

[config.settings]
type = "array"
items = "setting"
default = []
doc = "All settings will be written roughly once per minute."

[config.address]
type = "string"
default = "192.168.1.207"

[config.read_device_temperature]
doc = "If true, an additional channel device_temperature with units kelvin will be added."
type = "boolean"
default = true

[state]

[messages]
